const data = [
    [
        "Hebei Niguo Communication Technology Co., Ltd. /河北尼果通讯科技有限公司",
        "Hebei Yintaifu Communication Technology Co., Ltd. /河北银泰福通讯科技有限公司",
        "Wu'an Jiexinde Technology Co., Ltd. /武安市捷信德科技有限公司",
        "Xialing Air Conditioning Handan Co., Ltd. /夏菱空调邯郸有限责任公司",
        "North Austrian Titanium Nanotechnology Co., Ltd. /北方奥钛纳米技术有限公司",
        "Hebei Yinlong New Energy Co., Ltd. /河北银隆新能源有限公司",
        "Hebei Minghao Electric Co., Ltd. /河北铭浩电器有限公司",
    ],
    [
        "Wu'an Luochi Environmental Protection Technology Co., Ltd. /武安市洛驰环保科技有限公司",
        "Wu'an Borui Chemical Co., Ltd. /武安市博瑞化工有限公司",
        "Wu'an Ditiantai Agricultural Materials Co., Ltd. /武安市地天泰农资有限公司",
        "Wu'an Jinhai Industry and Trade Co., Ltd. /武安市金海工贸有限公司",
        "Wu'an Xingxing Chemical Co., Ltd. /武安市恒星化工有限公司",
        "Wu'an Annuo Lubricating Grease Factory /武安市安诺润滑油脂厂",
    ],
    [
        "Hebei Puyang Steel Co., Ltd.  (河北普阳钢佚有限公司)",
        "Wu'an Yuhua Iron and Steel Co., Ltd. (武安市裕华钢铁有限公司)",
        "Hebei Xinjin Iron and Steel Co., Ltd. (河北新金钢铁有限公司)",
        "Hebei Wenfeng Iron and Steel Co., Ltd. (河北文丰钢铁有限公司)",
        "Jinding Heavy Industry Co., Ltd. (金鼎重工股份有限公司)",
        "Wu'an Mingfang Iron and Steel Co., Ltd. (武安市明芳钢铁有限公司)",
        "Wu'an Dongrong Iron and Steel Co., Ltd. (武安市烘熔钢铁有限公司)",
        "Wu'an Xinhui Metallurgical Industry Co., Ltd. (武安市鑫汇冶金工业有限公司)",
        "Wu'an Wen'an Iron and Steel Co., Ltd. (武安市文安钢铁有限公司)",
        "Hebei Xinghua Iron and Steel Co., Ltd. (河北兴华钢铁有限公司)",
        "Wu'an Xinshan Iron and Steel Co., Ltd. (武安市鑫山钢铁有限公司)",
        "Hebei Longfengshan Casting Co., Ltd. (河北龙凤山铸业有限公司)",
        "Xinxing Casting Pipe Co., Ltd. (新兴铸管有限公司)",
        "Hebei Weimei Environmental Protection Equipment Technology Co., Ltd. / 河北威美环保设备科技有限公司",
        "Wu'an Leiyuan Materials Co., Ltd. / 武安市磊源物资有限公司",
        "Wu'an Dechengmao Trading Co., Ltd. / 武安市德诚茂贸易有限公司",
        "Wu'an Jinquan Building Materials Co., Ltd. / 武安市金泉建材有限公司",
        "Wu'an Yanghaiping Lime Factory / 武安市杨海平白灰厂",
        "Wu'an Yunhua Desulfurizer Co., Ltd. / 武安市云华脱硫剂有限公司",
        "Wu'an Qianrui Desulfurizer Co., Ltd. / 武安市钱锐脱硫剂有限公司",
        "Wu'an Taoyuan Environmental Protection Material Co., Ltd. / 武安市桃源环保材料有限公司",
        "Wu'an Leiyan Desulfurizer Co., Ltd. / 武安市磊炎脱硫剂有限公司",
    ],
    [
        "Hebei Xinjinwanli New Material Technology Co., Ltd. (河北新金万利新材料科技有限公司)",
        "Wu'an Aokeda Pipe Co., Ltd. (武安市奥科达制管有限公司)",
        "Hebei Qinhe Heavy Industry Metal Technology Co., Ltd. (河北秦合重科金属科技有限公司)",
        "Wu'an Wuji Steel Rolling Plant (武安市午汲轧钢厂)",
        "Leiyang Casting Co., Ltd. /雷阳铸业有限公司",
        "Wu'an Longtai Casting Co., Ltd. /武安市隆泰铸造 有限公司",
        "Wu'an Precision Steel Casting Factory /武安市精密铸钢厂",
        "Wu'an Jintieling Foundry /武安市金铁岭铸造厂",
        "Wu'an Zhenhong Industry and Trade Co., Ltd. /武安市震宏工贸 有限公司",
        "Wu'an Jianfeng Casting Co., Ltd. /武安市建峰铸造 有限公司",
        "Wu'an Jiangsuo Foundry Co., Ltd. /武安市江锁铸造 有限公司",
        "Wu'an Jingwu Metallurgical Casting Co., Ltd. /武安市京武冶金铸造 有限公司",
        "Wu'an Junxin Repair Factory /武安市骏鑫修造厂",
        "Wu'an Lushen Casting Co., Ltd. /武安市路神铸造 有限公司",
        "Wu'an Shizheng Cast Steel Co., Ltd. /武安市实正铸钢 有限公司",
        "Wu'an Baoding Casting Co., Ltd. /武安市宝鼎铸造 有限公司",
        "Wu'an Feixiang Metal Products Co., Ltd. /武安市飞翔金属制品 有限公司",
        "Wu'an Hongbin Casting Co., Ltd. /武安市红斌铸业 有限公司",
        "Wu'an Qichang Foundry Co., Ltd. /武安市起昌铸造 有限公司",
        "Wu'an Kunxin Casting Co., Ltd. /武安市坤鑫铸造 有限公司",
        "Wu'an Wuta Metallurgical Machinery Manufacturing Co., Ltd. /武安市武塔冶金机械制造有 限公司",
        "Wu'an Yanshi Mining Machinery Co., Ltd. /武安市延时矿山机械 有限公司",
        "Wu'an Yaozeng Casting Co., Ltd. /武安市耀増铸造 有限公司",
        "Wu'an Yongtian Casting Co., Ltd. /武安市永天铸业 有限公司",
        "Hebei Dingrun Intelligent Equipment Manufacturing Co., Ltd. /河北鼎润智能装备制造 有限公司",
        "Hebei Fulong Intelligent Equipment Manufacturing Co., Ltd. /河北富隆智能装备制造 有限公司",
        "Wu'an Keli Steel Co., Ltd. /武安市科力型钢 有限公司",
        "Wu'an Advance Casting Co., Ltd. /武安市前进铸造 有限公司",
        "Wu'an Kunxuan Metal Products Co., Ltd. /武安市坤铉金属制品 有限公司",
        "Wu'an Aojian Foundry /武安市奥赠铸造厂",
        "Gongshi Equipment Manufacturing Co., Ltd. /共氏装备制适有限公司",
        "Wu'an Aoda Iron Profile Co., Ltd. /武安市奥达借铁型材 有限公司",
        "Wu'an Hongcheng Casting Co., Ltd. /武安市鸿程铸造 有限公司",
        "Hengtong Valve Co., Ltd. /恒通阀门有限责任公司",
        "Wu'an Junchang Casting Co., Ltd. /武安市军昌铸造 有限公司",
        "Wu'an Shuaifeng Casting Co., Ltd. /武安市帅丰铸业 有限公司",
        "Wu'an Tianjia Casting Co., Ltd. /武安市天佳铸造 有限公司",
        "Wu'an Yang Tianning Foundry /武安市杨天宁铸造厂",
        "Wu'an Jiyunheng Casting Co., Ltd. /武安市冀运恒铸造 有限公司",
        "Wu'an Ruipu Money Industry Co., Ltd. /武安市瑞普钱业 有限公司",
        "Wu'an Yingbao Casting Co., Ltd. /武安市盈宝铸造 有限公司",
        "Gree (Wu'an) Precision Equipment Manufacturing Co., Ltd. /格力（武安）精密装备制造 有限公司",
        "Hebei Guixing Intelligent Equipment Manufacturing Co., Ltd. /河北柜兴智能装备制造 有限公司",
        "Hebei Hunan Intelligent Equipment Manufacturing Co., Ltd. /河北虎赧智能装备制造 有限公司",
    ],
    [
        "Shi'an Huiyou Standard Parts Co., Ltd. /式安市汇友标准件有限公司",
        "Wu'an Yongyi Fastener Manufacturing Co., Ltd. /武安市永亿紧固件制造有限公司",
        "Wu'an Zhuyou Standard Parts Manufacturing Co., Ltd. /武安市助友标准件制造有限公司",
        "Wu'an Ruicheng Fastener Manufacturing Co., Ltd. /武安市瑞成紧固件制造有限公司",
        "Wu'an Weisheng Fastener Manufacturing Co., Ltd. /武安市伟晟紧固件制逍有限公司",
        "Wu'an Shuangxin Machinery Parts Processing Factory /武安市双新机械配件加工厂",
        "Wu'an Zhandong Fastener Manufacturing Co., Ltd. /武安市占东紧固件制迪有限公司",
        "Jiangjie Steel Wire Processing Co., Ltd. /江杰钢丝加工有限公司",
        "Wu'an Zhuoxin Machinery Repair Factory /武安市卓信机械修配厂",
        "Wu'an Jiayou Machinery Equipment Sales Co., Ltd. /武安市佳优机械设备销售有限公司",
        "Wu'an Yongming Industrial and Mining Accessories Co., Ltd. /武安市永铭工矿配件有限公司",
        "Wu'an Shengyi Industry and Trade Co., Ltd. /武安市升亿工贸有限公司",
        "Zweig Electric (Beijing) Co., Ltd. Hebei Branch /茨威格电气（北京）有限公司 河北分公司",
        "Hebei Hanwu Cotton Machinery Co., Ltd. /河北邯武棉机有限公司",
        "Hebei Kewo Rail Transit Equipment Co., Ltd./ 河北科沃轨道交通装备有限公司",
        "Hebei Litongxing Auto Parts Co., Ltd. /河北利通行汽车配件有限公司",
        "Hebei Manzhuo Electronic Components Manufacturing Co., Ltd. /河北曼卓电子元器件制造有限公司",
        "Hebei Nuoen Water Purification Equipment Co., Ltd. /河北诺恩水净化设备有限公司",
        "Hebei Qianxing Metallurgical Machinery Co., Ltd. /河北乾兴冶金机械有限公司",
        "Hebei Wuma Metal Products Co., Ltd. /河北武马金属制品有限公司",
        "Hebei Zhaohong Mechanical Pump Industry Co., Ltd. /河北兆宏机械泵业有限公司",
        "Hebei Zhenggong Metallurgical Equipment Co., Ltd. /河北正工冶金设备有限公司",
        "Kewo Intelligent Equipment Technology Wu'an Co., Ltd. /科沃智能装备技术武安有限公司",
        "Wu'an Anya Transportation Facilities Co., Ltd. /武安市安亚交通设施有限公司",
        "Wu'an Bestar Industry and Trade Co., Ltd /武安市贝斯达工贸有限公司",
        "Wu'an Mansu Environmental Protection Technology Co., Ltd. /武安市满宿环保科技有限公司",
        "Handan City Hanwu Cotton Machine Factory /邯郸市邯武棉机厂",
        "Wu'an Hongqin Mechanical Pump Industry Co., Ltd. /武安市宏秦机械泵业有限公司",
        "Wu'an Jingcheng Machinery Equipment Technology Co., Ltd. /武安市精诚机械设备科技有限公司",
        "Wu'an Tongda Machinery Co., Ltd. /武安市通达机械有限公司",
        "Wu'an Zhenyi Casting Material Co., Ltd. /武安市真谀铸造材料有限公司",
        "Zhongwo Rail Transit Equipment (Wu'an) Co., Ltd. /中沃轨道交通装备（武安）有限公司",
        "Handan Yiyi New Energy Technology Co., Ltd. /邯郸一一新能源科技有限公司",
        "Wu'an Jijia Building Materials Machinery Co., Ltd. /武安市冀佳建材机械有限公司",
        "Wu'an Yongsheng Mechanical Pump Industry Co., Ltd. /武安市永盛机械泵业有限公司",
        "Hebei Yawei Environmental Protection Technology Co., Ltd. /河北雅威环保科技有限公司",
        "Wu'an Xiangrui Renewable Resources Utilization Co., Ltd. /武安市祥瑞再生资源利用有限公司",
        "Wu'an Jiayou Metallurgical Equipment Co., Ltd. /武安市佳友冶金设备有限公司",
        "Wu'an Shuojin Casting Co., Ltd. /武安市硕金铸造有限公司",
        "Wu'an Luwu Metal Cutting Co., Ltd. /武安市履武金属切割有限公司",
        "Wu'an Hongxu Hezi Overlay Welding Factory /武安市宏旭鶴子堆焊厂",
        "Wu'an Dongshan Bomb Skip Manufacturing Co., Ltd. /武安市东山弹箕制造有限公司",
        "Hebei Xinwuan Iron and Steel Group Pantai Metal Parts Manufacturing Co., Ltd. /河北新武安钢铁集团盼泰金属件制造 有限公司",
        "Wu'an Sanjia Metallurgical Parts Co., Ltd. /武安市三佳冶金配件有限公司",
        "Wu'an Changde Machinery Co., Ltd. /武安市昌德机械有限公司",
        "Wu'an Hengjiu Machine Repair Factory /武安市恒久机修厂",
        "Wu'an City Tushan Township Jinhe Repair Factory /武安市土山乡金河修造厂",
        "Handan Shengyi Metal Doors and Windows Co., Ltd. /邯郸市盛艺金属门窗有限公司",
        "Wu'an Shichang Machinery Parts Co., Ltd. /武安市世昌机械配件有限公司",
        "Wu'an Tiansheng Machinery Repair Factory /武安市天盛机械修配厂",
        "Wu'an Zhengri Machinery Equipment Co., Ltd. /武安市正日机械设备有限公司",
        "Changfeng Machinery Factory /常丰机械厂",
    ],
    [
        "Wu'an Xinfeng Cement Co., Ltd. (武安市新峰水泥有限责任公司)",
        "Handan Daqiao Cement Co., Ltd. (邯郸市大桥水泥有限公司)",
        "Wu'an Zijinshan Cement Plant (武安市紫金山水泥厂)                                                                                                                                                             ",
        "Wu'an Hanwu Cement Plant (武安市邯武水泥厂)",
        "Wu'an Kangli Cement Manufacturing Co., Ltd. (武安市康力水泥制造有限公司)",
        "Wu'an Gushan Cement Co., Ltd. (武安市鼓山水泥有限公司)",
        "Wu'an Jinruifeng Cement Manufacturing Co., Ltd. (武安市金瑞峰水泥制造有限公司)",
        "Wu'an No.3 Cement Plant (武安市第三水泥厂)",
        "Wu'an Shenhongqi Cement Plant (武安审红旗水泥厂)",
        "Wu'an Baoshida Cement Manufacturing Co., Ltd. (武安市保事达水泥制造有限公司)",
        "China Coal First Construction Co., Ltd. Building Materials Factory (中煤第一建设有限公司建筑材料厂)",
        "Hebei Shitaishan Cement Co., Ltd. (河北石台山水泥有限公司)",
        "Wu'an Yuanbaoshan Industrial Group Cement Co., Ltd. (武安市元宝山工业集团水泥有限公司)",
        "Wu'an Xingshan Cement Co., Ltd. (武安市兴山水泥有限公司)",
        "Handan Guxing Cement Plant (邯郸市鼓兴水泥厂)",
        "Wu'an Ruiyun Cement Co., Ltd. (武安市瑞云水泥有限公司)",
        "Wu'an Zifeng Building Materials Co., Ltd. /武安市紫峰建材有限公司",
        "Wu'an Dinghao Building Materials Co., Ltd. /武安市鼎豪建材有限公司",
        "Wu'an Shunyao Building Materials Co., Ltd. /武安市顺耀建材有限公司",
        "Wu'an Dayao Building Materials Co., Ltd. /武安市大尧建材有限公司",
        "Wu'an Ruiye Building Materials Co., Ltd. /武安市瑞冶建材有限公司",
        "Shi'an Guangxuan Building Materials Co., Ltd. /式安市广选建筑材料有限公司",
        "Shi'an Xuefeng White Ash Co., Ltd. /式安市学峰白灰有限公司",
        "Wu'an Gangyu Lime Co., Ltd. /武安市钢钰白灰有限公司",
        "Chi'an Dingli Building Materials Co., Ltd. /击安市鼎立建材有限公司",
        "Wu'an Bokang Calcium Carbonate Co., Ltd. /武安市博康碳酸钙有限公司",
        "Wu'an Chengsheng Building Materials Co., Ltd. (武安市成胜建材有限公司)",
        "Wu'an Pingshun Building Materials Co., Ltd. (武安市憑顺建材有限公司)",
        "Wu'an Xinrong Building Materials Co., Ltd. (武安市欣荣建材有限公司)",
        "Wu'an Yansheng Building Materials Co., Ltd. (武安市炎盛建材有限公司)",
        "Wu'an Yanding Building Materials Co., Ltd. (武安市炎鼎建材有限公司)",
        "Wu'an Huifang Building Materials Co., Ltd. (武安市会芳建材有限公司)",
        "Wu'an Bangtai Building Materials Co., Ltd. (武安市邦泰建材有限公司)",
        "Wu'an Shunzhi Building Materials Co., Ltd. (武安市顺志建材有限公司)",
        "Wu'an Yicheng Building Materials Co., Ltd. (武安市亿诚建材有限公司)",
        "Wu'an Tian'an Building Materials Co., Ltd. (武安市天安建材有限公司)",
        "Wu'an Xingyi Building Materials Co., Ltd. (武安市兴亿建材有限公司)",
        "Wu'an Douxin Building Materials Co., Ltd. (武安市斗鑫建材有限公司)",
        "Wu'an Zengjin Building Materials Co., Ltd. (武安市增金建材有限公司)",
        "Wu'an Xiangzong Building Materials Co., Ltd. (武安市祥宗建材有限公司)",
        "Wuan Longpeng Building Materials Co., Ltd. (武安龙鹏建材有限公司)",
        "Wu'an Minglong Building Materials Co., Ltd. (武安市铭龙建材有限公司)",
        "Wu'an Huoyanshan Industrial Co., Ltd. (武安市火焰山工业有限公司)",
        "Wu'an Wurui Nanometer Calcium Industry Co., Ltd. (武安市吴瑞钠米钙业有限公司)",
        "Wu'an Yacheng Lime Co., Ltd. (武安市亚成白灰有限公司)",
        "Wu'an Yuntian Lime Co., Ltd. (武安市云天白灰有限公司)",
        "Wu'an Qitian Building Materials Co., Ltd. (武安市启天建材有限公司)",
        "Wu'an Xing'an Building Materials Co., Ltd. (武安市兴安建材有限公司)",
        "Wu'an Zhenghao Lime Co., Ltd. (武安市正浩白灰有限公司)",
        "Wu'an Ruiguan Building Materials Co., Ltd. (武安市瑞观建材有限公司)",
        "Wu'an Lanxin Building Materials Co., Ltd. (武安市蓝新建材有限公司)",
        "Wu'an Quanli Building Materials Co., Ltd. (武安市全利建材有限公司)",
        "Wu'an Shengxiao Lite Ash Co., Ltd. (武安市胜晓白灰有限公司)",
        "Wu'an Puhao Building Materials Co., Ltd. (武安市普浩建材有限公司)",
        "Hebei Xingte Building Materials Co., Ltd. (河北星特建材有限公司)",
        "Wu'an Dongjinxin Calcium Carbonate Co., Ltd. (武安市东金鑫碳酸钙有限公司)",
        "Wu'an Chenhang Building Materials Co., Ltd. (武安市晨航建材有限公司)",
        "Wu'an Ronghui Building Materials Co., Ltd. (武安市荣辉建材有限公司)",
        "Wu'an Shengfeng Building Materials Co., Ltd. (武安市圣丰建材有限公司)",
        "Wu'an Yujin Building Materials Co., Ltd. (武安市宇金建材有限公司)",
        "Wu'an Nanyang Yishan Calcium Industry Co., Ltd. (武安市南洋移山钙业有限公司)",
        "Wu'an Huaxuan Building Materials Co., Ltd. (武安市华铉建材有限公司)",
        "Wu'an Shuntian Industry and Trade Co., Ltd. (武安市顺天工贸有限公司)",
        "Wu'an Wanxing Building Materials Co., Ltd. (武安市万兴建材有限公司)",
        "Wu'an Zhenshen Building Materials Co., Ltd. (武安市振申建材有限公司)",
        "Hebei Longchang Building Materials Co., Ltd. (河北隆昶建材有限公司)",
        "Hebei Wanchang Calcium Industry Co., Ltd. (河北万昌钙业有限公司)",
        "Wu'an Longshun Building Materials Co., Ltd. (武安市隆顺建材有限公司)",
        "Wu'an Jinding Building Materials Co., Ltd. (武安市金鼎建材有限公司)",
        "Wu'an Zhenxu Cement Products Co., Ltd. (武安市震旭水泥制品有限公司)",
        "Wu'an Haojunsheng Cement Products Co., Ltd. (武安市郝军生水泥制品有限公司)",
        "Wu'an Kangsheng Cement Products Co., Ltd. (武安市康盛水泥制品有限公司)",
        "Wu'an Liliang Cement Products Co., Ltd. (武安市利亮水泥制品有限公司)",
        "Wu'an Sengmin Cement Products Co., Ltd. (武安市僧民水泥制品有限公司)",
        "Wu'an Leiyu Cement Products Co., Ltd. (武安市磊裕水泥制品有限公司)",
        "Wu'an Yanwei Cement Products Co., Ltd. (武安市彦伟水泥制品有限公司)",
        "Wu'an Zhonghao Building Materials Co., Ltd. (武安市众昊建材有限公司)",
        "Wu'an Weibin New Wall Material Co., Ltd. (武安市卫斌新型墙体材料有限公司)",
        "Wu'an Xueshu Cement Products Co., Ltd. (武安市学书水泥制品有限公司)",
        "Wu'an Luoxing New Wall Material Co., Ltd. (武安市洛星新型墙体材料有限公司)",
        "Wu'an Anping Concrete Co., Ltd. (武安市安平混凝土有限公司)",
        "Hebei Xunze Road Engineering Co., Ltd. (河北汛泽道路工程有限公司)",
        "Wu'an Kangbo Kaolin Co., Ltd. (武安市康伯高岭土有限公司)",
        "Wu'an Haoze Environmental Protection Technology Co., Ltd. (武安市浩泽环保科技有限公司)",
        "Hebei Nengtong Bridge Engineering Co., Ltd. (河北能通路桥工程有限公司)",
        "Wu'an Hengrong Industry and Trade Co., Ltd. (武安市恒荣工贸有限公司)",
        "Wu'an Jinyuan New Wall Material Co., Ltd. (武安市金园新型墙体材料有限公司)",
        "Wu'an Guangzhou Cement Products Factory (武安市广洲水泥制品厂)",
        "Wu'an Shenzhiwu Cement Brick Factory (武安市申志武水泥砖厂)",
        "Wu'an Liming Building Materials Co., Ltd. (武安市利明建筑材料有限公司)",
        "Wu'an Bofeite Environmental Protection Technology Co., Ltd. (武安市博飞特环保科技有限公司)",
        "Wu'an Huayi New Building Materials Co., Ltd. (武安市华毅新型建筑材料有限公司)",
        "Wu'an Shuofeng New Wall Material Co., Ltd. (武安市硕丰新型墙体材料有限公司)",
        "Wu'an Qiguan New Wall Material Co., Ltd. (武安市企冠新型墙依材料有限公司)",
        "Wu'an Hongsen New Wall Material Co., Ltd. (武安市宏森新型墙体材料有限公司)",
        "Wu'an Zhongfu New Wall Material Co., Ltd. (武安市众福新型墙体材料有限公司)",
        "Hebei Zichen Super High Water Material Co., Ltd. (河北紫晨超高水材料有限公司)",
        "Wu'an Guifeng Unburned Brick Factory (武安市贵峰免烧砖厂)",
        "Wu'an Yunhui Unburned Brick Factory (武安市云辉免烧砖厂)",
        "Wu'an Jinleishun Building Materials Co., Ltd. (武安市金羸顺建材有限公司)",
        "Wu'an Jingrui Trading Co., Ltd. (武安市晶瑞贸易有限公司)",
        "Wu'an Fukai Concrete Co., Ltd. (武安市富凯混凝土有限公司)",
        "Zhuwu New Wall Material Co., Ltd. (铸武新型墙体材料有限公司)",
        "Wu'an Huizhitong Cement Co., Ltd. (武安市汇智通水泥有限公司)",
        "Wu'an Suyuan Cement Products Co., Ltd. (武安市速源水泥制品有限公司)",
        "Wu'an Henghui New Wall Material Co., Ltd. (武安市恒辉新型墙体材料有限公司)",
        "Wu'an Hengyu New Wall Material Co., Ltd. (武安市恒裕新型墙体材料有限公司)",
        "Wu'an Yihui Trading Co., Ltd. (武安市亿辉贸易有限公司)",
        "Wu'an Jiaye New Building Materials Co., Ltd. (武安市佳业新型建材有限公司)",
        "Wu'an Xihu Zhenxing Cement Products Factory (武安市西湖振兴水泥制品厂)",
        "Wu'an Haiquan Cement Products Co., Ltd. (武安市海全水泥制品有限公司)",
        "Wu'an Jiajiawang New Building Materials Co., Ltd. (武安市家家旺新型建材有限公司)",
        "Wu'an Boyuan New Wall Material Co., Ltd. (武安市博远新型墙体材料有限公司)",
        "Wu'an Xuguang Unburned Brick Factory (武安市旭光免烧砖厂)",
        "Wu'an Zhendong New Wall Material Co., Ltd. (武安市振东新型墙体材料有限公司)",
        "Wu'an Dongfeng New Wall Material Co., Ltd. (武安市东峰新型墙体材料有限公司)",
        "Yuanbaoshan Industrial Group Brick and Tile Co., Ltd. (元宝山工业集团砖瓦有限公司)",
        "Hebei Harmony Sand Rhyme Environmental Protection Technology Co., Ltd. (河北和谐砂韵环保科技有限公司)",
        "Wu'an Yetao Town Dating Brick Factory (武安市冶陶镇交友砖厂)",
        "Wu'an Hongbang New Wall Material Co., Ltd. (武安市宏邦新型墙体材料有限公司)",
        "Wu'an Xinfeng Concrete Co., Ltd. (武安市新蜂混凝土有限公司)",
        "Wu'an Leihuanxin Construction Machinery Co., Ltd. (武安市磊焕鑫工程机械施工有限公司)",
        "Branch of Wu'an Ruisheng Concrete Co., Ltd. (武安市瑞升混凝土有限公司分公司)",
        "Wu'an Fuyun Concrete Co., Ltd. (武安市富运混凝土有限公司)",
        "Wu'an Shangqiang Cement Products Co., Ltd. (武安市商腔水泥制品有限公司)",
        "Wu'anjin Municipal Engineering Company (武安巾市政工程公司)",
        "Wu'an First Construction Engineering Co., Ltd. (武安市第一建筑工程有限公司)",
        "Wu'an Taixing Concrete Co., Ltd. (武安市泰兴混凝土有限公司)",
        "Wu'an Xincheng Concrete Co., Ltd. (武安市鑫诚混凝土有限公司)",
        "Wu'an Fuyun Concrete Co., Ltd. (武安市富运混凝土有限公司 磁山分公司)",
        "Wu'an Mingcheng Concrete Co., Ltd. (武安市铭诚混凝土有限公司)",
        "Wu'an Jijutian Brick Factory (武安市冀聚田砖厂)",
        "Wu'an Linghe Coal and Stone Porous Brick Factory (武安市灵河煤歼石多孔砖厂)",
        "Wu'an Runda New Wall Material Co., Ltd. (武安市润达新型墙体材料有限公司)",
        "Wu'an Jianxing Stalk Stone Brick Factory (武安市建兴秆石砖厂)",
        "Wu'an Shenyu New Wall Material Co., Ltd. (武安市申宇新型墙体材料有限公司)",
        "Wu'an Xianqiang Building Materials Co., Ltd. (武安市现强建材有限公司)",
        "Wu'an Xinpengsi Wall Material Co., Ltd. (武安市新鹏斯型墙依材料有限公司)",
        "Wu'an Xinpeng Building Material Factory (武安市鑫朋建材厂)",
        "Wu'an Yanhua Jianshi Brick Factory (武安市艳华歼石砖厂)",
        "Wu'an Jianzhou Building Materials Co., Ltd. (武安市建周建材有限公司)",
        "Wu'an Wangfuzeng Brick Factory (武安市王福增砖厂)",
        "Wu'an Xuemin Wall Materials Manufacturing Co., Ltd. (武安市学敏墙材制造有限公司)",
        "Wu'an Youfang Jianshi Brick Factory (武安市有方歼石砖厂)",
        "Wu'an Soil Change Plate New Wall Material Co., Ltd. (武安市土换盘新型墙体材料有限公司)",
        "Wu'an Guangshun New Wall Material Co., Ltd. (武安市广顺新型墙体材料有限公司)",
        "Wu'an Wanggan New Wall Material Co., Ltd. (武安市王乾新型墙体材料有限公司)",
        "Wu'an Yongding Coal and Stone Brick Factory (武安市永鼎煤歼石砖厂)",
        "Wu'an Liangde New Wall Material Co., Ltd. (武安市亮德新型墙材有限公司)",
        "Wu'an Guangxin New Wall Material Co., Ltd. (武安市广鑫新型墙体材料有限公司)",
        "Wu'an Kaoshi New Wall Materials Co., Ltd. (武安市考时新型墙材有限公司)",
        "Wu'an Zengyu New Wall Material Co., Ltd. (武安市增玉新型墙体材料有限公司)",
        "Wu'an Zhenping Brick Factory (武安市振平砖厂)",
        "Wu'an Huameng New Wall Material Co., Ltd. (武安市华梦新型墙体材料有限公司)",
        "Wu'an Longqing New Wall Material Co., Ltd. (武安市龙庆新型墙体材料有限公司)",
        "Wu'an Qidong New Wall Material Co., Ltd. (武安市启东新型墙体材料有限公司)",
        "Wu'an Qinkunshan New Wall Material Co., Ltd. (武安市秦坤山新型墙体材料有限公司)",
        "Wu'an Shengfeng New Building Materials Co., Ltd. (武安市盛烽新型建材有限公司)",
        "Wu'an Xianqu New Wall Material Co., Ltd. (武安市现区新型墙体材料有限公司)",
        "Wu'an Luosheng New Wall Material Co., Ltd. (武安市洛盛新型墙体材料有限公司)",
        "Wu'an Yueqiang New Wall Material Co., Ltd. (武安市月强新型墙体材料有限公司)",
        "Wu'an Panjiao New Wall Yi Material Co., Ltd. (武安市盘交新型墙依材料有限公司)",
        "Wu'an Puxin New Wall Material Co., Ltd. (武安市普鑫新型墙体材料有限公司)",
        "Wu'an Zhenting New Wall Material Co., Ltd. (武安市镇廷新型墙体材料有限公司)",
        "Wu'an Yinglong Glue Solid Powder Co., Ltd. / 武安市英龙胶固粉有限公司",
        "Wu'an Yunxi Glue Solid Powder Co., Ltd. /武安市云西胶固粉有限公司",
        "Wu'an Sushan Glue Solid Powder Co., Ltd. /武安市粟山胶固粉有限公司",
        "Wu'an Jijutian Brick Factory (武安市冀聚田砖厂)",
        "Wu'an Linghe Coal and Stone Porous Brick Factory (武安市灵河煤歼石多孔砖厂)",
        "Wu'an Runda New Wall Material Co., Ltd. (武安市润达新型墙体材料有限公司)",
        "Wu'an Jianxing Stalk Stone Brick Factory (武安市建兴秆石砖厂)",
        "Wu'an Shenyu New Wall Material Co., Ltd. (武安市申宇新型墙体材料有限公司)",
        "Wu'an Xianqiang Building Materials Co., Ltd. (武安市现强建材有限公司)",
        "Wu'an Xinpengsi Wall Material Co., Ltd. (武安市新鹏斯型墙依材料有限公司)",
        "Wu'an Xinpeng Building Material Factory (武安市鑫朋建材厂)",
        "Wu'an Yanhua Jianshi Brick Factory (武安市艳华歼石砖厂)",
        "Wu'an Jianzhou Building Materials Co., Ltd. (武安市建周建材有限公司)",
        "Wu'an Wangfuzeng Brick Factory (武安市王福增砖厂)",
        "Wu'an Xuemin Wall Materials Manufacturing Co., Ltd. (武安市学敏墙材制造有限公司)",
        "Wu'an Youfang Jianshi Brick Factory (武安市有方歼石砖厂)",
        "Wu'an Soil Change Plate New Wall Material Co., Ltd. (武安市土换盘新型墙体材料有限公司)",
        "Wu'an Guangshun New Wall Material Co., Ltd. (武安市广顺新型墙体材料有限公司)",
        "Wu'an Wanggan New Wall Material Co., Ltd. (武安市王乾新型墙体材料有限公司)",
        "Wu'an Yongding Coal and Stone Brick Factory (武安市永鼎煤歼石砖厂)",
        "Wu'an Liangde New Wall Material Co., Ltd. (武安市亮德新型墙材有限公司)",
        "Wu'an Guangxin New Wall Material Co., Ltd. (武安市广鑫新型墙体材料有限公司)",
        "Wu'an Kaoshi New Wall Materials Co., Ltd. (武安市考时新型墙材有限公司)",
        "Wu'an Zengyu New Wall Material Co., Ltd. (武安市增玉新型墙体材料有限公司)",
        "Wu'an Zhenping Brick Factory (武安市振平砖厂)",
        "Wu'an Huameng New Wall Material Co., Ltd. (武安市华梦新型墙体材料有限公司)",
        "Wu'an Longqing New Wall Material Co., Ltd. (武安市龙庆新型墙体材料有限公司)",
        "Wu'an Qidong New Wall Material Co., Ltd. (武安市启东新型墙体材料有限公司)",
        "Wu'an Qinkunshan New Wall Material Co., Ltd. (武安市秦坤山新型墙体材料有限公司)",
        "Wu'an Shengfeng New Building Materials Co., Ltd. (武安市盛烽新型建材有限公司)",
        "Wu'an Xianqu New Wall Material Co., Ltd. (武安市现区新型墙体材料有限公司)",
        "Wu'an Luosheng New Wall Material Co., Ltd. (武安市洛盛新型墙体材料有限公司)",
        "Wu'an Yueqiang New Wall Material Co., Ltd. (武安市月强新型墙体材料有限公司)",
        "Wu'an Panjiao New Wall Yi Material Co., Ltd. (武安市盘交新型墙依材料有限公司)",
        "Wu'an Puxin New Wall Material Co., Ltd. (武安市普鑫新型墙体材料有限公司)",
        "Wu'an Zhenting New Wall Material Co., Ltd. (武安市镇廷新型墙体材料有限公司)",
    ],
    [
        "Wu'an Jinyan Thermal Insulation Material Co., Ltd. /武安市金岩保温材料有限公司",
        "Wu'an Zhaofu Thermal Insulation Material Co., Ltd. /武安市钊復保温材料有限公司",
        "Wu'an Shengjin Waste Residue Comprehensive Utilization Co., Ltd. /武安市胜金废渣综合利用有限公司",
        "Handan Shengkai Environmental Protection Technology Co., Ltd. /邯郸市胜凯环保科技有限公司",
        "Wu'an Yumin Thermal Insulation Material Co., Ltd. /武安市煜民保温材料有限公司",
        "Hebei Weifeng Thermal Insulation Material Co., Ltd. /河北威蜂保温材料有限公司",
        "Hebei Houyao Environmental Protection Technology Co., Ltd./河北厚耀环保科技有限公司",
        "Wu'an Guangyi Insulation Material Factory /武安市广义保温材料厂",
        "Wu'an Jinge Thermal Insulation Material Co., Ltd. /武安市金格保温材料有限公司",
    ],
    [
        "Wu'an Fengyue Refractories Co., Ltd. /武安市峰跃耐火材料有限公司",
        "Wu'an Wanpeng Refractories Co., Ltd. /武安市万鹏耐火材料有限公司",
        "Wu'an Zhenjiang Materials Industry and Trade Co., Ltd. /武安市振江物资工贸有限公司",
        "Wu'an Xinchen Refractories Co., Ltd. /武安市新晨耐火材料有限公司",
        "Wu'an Yinshun Refractories Co., Ltd.  武安市银顺耐火材料有限公司",
        "Wu'an Permanent Industry and Trade Co., Ltd. /武安市永久工贸有限公司",
        "Wu'an Shuangyou Furnace Material Economic and Trade Co., Ltd. /武安市双友炉料经贸有限公司",
        "Wu'an Jinshi Non-metallic Material Factory /武安市金石非金属材料厂",
        "Wu'an Shengzhan Refractories Co., Ltd. / 武安市升展耐火材料有限公司",
        "Wu'an Yuhao Refractories Co., Ltd. /武安市宇昊耐火材料有限公司",
        "Wu'an Rongxin charge / 武安市荣鑫炉料",
        "Wu'an Rongxi Refractory Forest Material Processing Factory /武安市荣熙耐火林料加工厂",
        "Wu'an Minghe Insulation Refractory Material Factory / 武安市名河保温耐火材料厂",
        "Hebei Xinwuan Steel Support Group Rongyu Refractories Co., Ltd. /河北新武安钢扶集团荣煜耐火材料有限公司",
        "Wu'an Junhui Trading Co., Ltd. Refractory Material Processing Plant /武安市军辉贸易有限公司耐火材料加工厂",
        "Wu'an Haorun Industry and Trade Co., Ltd. /武安市昊润工贸有限公司",
    ],
    [
        "Wu'an Jiantai Grain and Oil Co., Ltd. /武安市健泰粮油有限公司",
        "Wu'an Furuikang Oil Co., Ltd. /武安市福瑞康油脂有限公司",
        "Hebei Cangshengxing Grain and Oil Industry and Trade Co., Ltd. /河北仓盛兴粮油工贸有限公司",
        "Wu'an Boyan Pioneer Flour Mill /武安市伯延先锋面粉厂",
        "Hebei Huarui Nongyuan Millet Processing Co., Ltd. /河北华瑞农源小米加工有限公司",
        "Wu'an Genuine Agricultural Technology Co., Ltd. /武安市正品 农业科技有限公司",
        "Wu'an Maixiang Flour Processing Co., Ltd. /武安市麦香面粉加工有限公司",
        "Hebei Tianao Development Agriculture Co., Ltd. /河北田奥开发农业有限公司",
        "Wu'an Wuwai Gold Products Co., Ltd. /武安市物外金品有限公司",
        "Hebei Gongbei Food Co., Ltd. /河北拱北食品有限公司",
        "Wu'an Laixing Vinegar Co., Ltd. /武安市来兴香醋有限公司",
        "Wu'an Shanlaotou Vinegar Industry Co., Ltd. /武安市山老头醋业 有限公司",
        "Wu'an Madiantou Longevity Vinegar Factory /武安市马店头长寿香醋厂",
        "Luoheyuan Balsamic Vinegar Factory, Living Water Township, Wu'an City /武安市活水乡 洛河源香醋厂",
        "Wu'an Yongkangjia Dumpling Processing Factory /武安市永康佳水饺加工厂",
        "Handan Kangyuan Food Co., Ltd. /邯郸市康源喰品有限公司",
        "Hebei Dagu Special Breeding Development Co., Ltd. /河北大鹘特种种养开发 有限公司",
        "Wu'an Zhaodu Junpin Co., Ltd. /武安市赵都俊品有限公司",
        "Wu'an Xuri Dumpling Processing Factory /武安市旭日水饺加工厂",
        "Wu'an Hanbo Pastry Distribution Department /武安市韩波糕点经销部",
        "Wu'an Jiuhun Liquor Industry Co., Ltd. /武安市酒魂酒业有限公司",
        "Wu'an Jiuyuan Liquor Industry Co., Ltd. /武安市酒源酒业有限公司",
        "Hebei Songzu Liquor Industry Co., Ltd. /河北宋祖酒业有限公司",
        "Hebei Tiandao Liquor Industry Co., Ltd. /河北天道酒业股份有限公司",
        "Hebei Wanshouquan Liquor Industry Co., Ltd. /河北万寿泉酒业有限公司",
        "Hebei Lidong Beverage Co., Ltd. /河北立动饮品有限公司",
    ],
    [
        "Wu'an Baifu Furniture Co., Ltd. /武安市百福家具有限公司",
        "Wu'an Garuda Wood Industry Co., Ltd. /武安市金翅鸟木业有限公司",
        "Wu'an Xitushan Township Xinchao Woodenware Factory /武安市西土山乡新潮木器厂",
    ],
    [
        "Wu'an Xiaosai Sole Processing Co., Ltd. /武安市逍赛鞋底加工有限公司",
        "Wu'an Caisheng Latex Products Co., Ltd. /武安市彩升乳胶制品有限公司",
        "Wu'an Zhaolei Wire Manufacturing Co., Ltd. /武安市召磊电线制造有限公司",
        "Wu'an Junmao Rubber and Plastic Products Co., Ltd. /武安市骏茂橡塑制品有限公司",
        "Wu'an Hengde Processing Factory /武安市恒德加工厂",
        "Wu'an Bolihaojin Packaging Products Co., Ltd. /武安市博利豪金包装制品有限公司",
        "Zhangjiagang Ruixin Low Carbon Pipe Industry Co., Ltd. /张家港瑞新低碳管业有限公司武安分公司",
        "Wu'an Huamao Optical Material Co., Ltd. /武安市华茂光学材料有限公司",
        "Handan Yaxing Construction Plastic Pipe Co., Ltd. /邯郸市亚星建塑管业有限公司",
        "Wu'an Dongsu Pipe Industry Co., Ltd. /武安市东塑管业有限公司",
    ],
    [
        "Wu'an is now adding a concentrator /武安市现增选矿厂",
        "Wu'an Chengke Concentrator /武安市成科选矿厂",
        "Wu'an Xinhai Mineral Processing Co., Ltd. /武安市鑫海选矿有限公司",
        "Wu'an Liangyun Mineral Processing Co., Ltd. /武安市良运选矿有限公司",
        "Wu'an Longteng Concentrator /武安市龙腾选矿厂",
        "Wu'an Xiqueling Concentrator /武安市喜鹊岭选矿厂",
        "Wu'an Tianchuang Industry and Trade Co., Ltd. /武安市天创工贸有限公司",
        "Wu'an Yuheng Industry and Trade Co., Ltd. /武安市誉恒工贸有限公司",
        "Wu'an Mingxiu Industry and Trade Co., Ltd. /武安市明秀工贸有限责任公司",
        "Handan Jinhua Concentrator /邯郸市金华选矿厂",
        "Wu'an Jianshan Beigou Waste Residue Comprehensive Recycling Plant /武安市尖山北沟废渣综合再生利用厂",
        "Wu'an Xinli Concentrator /武安市鑫利选矿厂",
        "Longxiang Concentrator, Kuangshan Town, Wu'an City /武安市矿山镇龙翔选厂",
        "Wu'an Haibo Industry and Trade Co., Ltd. Xinwang Concentrato /武安市海博工贸有限公司鑫旺选矿厂",
        "Wu'an Haiyuan Concentrator /武安市海源选矿厂",
        "Wu'an Li Jinsheng Industry and Trade Co., Ltd. /武安市李金生工贸有限公司",
        "Wu'an Tuancheng Xishan Concentrator /武安市团城西山选矿厂",
        "Wu'an Jiaxin Concentrator /武安市佳鑫选矿厂",
        "Wu'an Ronghe Concentrator /武安市荣和选矿厂",
        "Wu'an Lianyun Mineral Processing Co., Ltd. /武安市联运选矿有限公司",
        "Wu'an Hongya Concentrator /武安市宏亚选矿厂",
        "Wu'an Changyuan Concentrator /武安市昌源选矿厂",
        "Wu'an Xiyingjing Zhenxing Concentrator /武安市西营井振兴选矿厂",
        "Wu'an Jinhong Mineral Concentrator  /武安市金宏选矿厂（普通合伙人）",
        "Wu'an Jinda Concentrator /武安市进达选矿厂",
        "Fuxin Mineral Concentrator in Shangtuan Township, Wu'an City /武安市上团城乡福鑫选矿厂",
        "Wu'an Longxin Mineral Processing Co., Ltd. /武安市珑欣选矿有限公司",
        "Concentrator in Xiaobeizhuang Village, Chongyi Township, Wu'an City /武安市崇义乡小北庄村选矿厂",
        "Wu'an Dongwa Concentrator /武安市东洼选厂",
        "Wu'an Zhongda Industry and Trade Co., Ltd. /武安市众达工贸有限公司",
        "Wu'an Zhaozhuang Concentrator /武安市赵庄选矿厂",
        "Wu'an Chengda Materials Co., Ltd. /武安市诚达物资有限公司",
        "Wu'an Chengliang Washing Co., Ltd. /武安市成亮洗选有限公司",
        "Wu'an Hezhuang Lianban Mineral Concentrator /武安市贺庄联办选矿厂",
        "Wu'an Wanxing Iron Mine Concentrator /武安市万兴鉄矿选矿厂",
        "Wu'an Beibaishi Village Concentrator /武安市北白石村办3号选厂",
        "Wu'an Leizhong Concentrator /武安市磊众选矿厂",
        "Wu'an Meikai Industry and Trade Co., Ltd. /武安市美凯工贸有限公司",
        "Diantou Concentrator of Wuji Town, Wu'an City /武安市午汲镇店头选矿厂",
        "Wu'an Yunlong Mineral Products Processing Factory /武安市云龙矿产品加工厂",
        "Wu'an Haili Concentrator /武安市海利选矿厂",
        "Wuji Town Concentrator /午汲镇选矿厂",
        "Wu'an Fushun Concentrator /武安市福顺选厂",
        "Wu'an Dahezhuang Yushan Concentrator /武安市大贺庄玉山选矿厂",
        "Wu'an Fuyun Concentrator /武安市福运选矿厂",
        "Wu'an Xinzhong Concentrator /武安市鑫众选矿厂",
        "Yanlong Concentrator of Wuji Town, Wu'an City /武安市午汲镇延龙选矿厂",
        "Quanwang Concentrator in Xiguang Village, Wu'an City /武安市西广村全旺选矿厂",
        "Wu'an Chengguo Concentrator /武安市承国选厂",
        "Huyou Concentrator in Fengdian Village, Wu'an City /武.安市蜂店村互友选厂",
        "Wu'an Dahezhuang Yuanxin Concentrator /武安市大贺庄源鑫选矿厂",
        "Wu'an Manfa Polymer Co., Ltd. /武安市满发聚有限公司",
        "Wu'an Yideshun Industry and Trade Co., Ltd. /武安市义得顺工贸有限公司",
        "Wu'an Gushan Xingsheng Concentrator /武安市固山兴盛选厂",
        "Wu'an Guolei Washing Co., Ltd./武安市国雷洗选有限公司",
        "Xiaowang Luchang Mineral Concentrator in Sizhuang Township, Wu'an City /武安市寺庄乡小汪禄昌选矿厂",
        "Wu'an Hongbao Washing Co., Ltd. /武安市鸿宝洗选有限公司",
        "Hebei Chenmei Industry and Trade Co., Ltd. /河北辰美工贸有限公司",
        "Wu'an Hongli Mineral Products Processing Factory /武安市宏利矿产品加工厂",
        "Wu'an Huadong Mineral Products Processing Factory /武安市华东矿产品加工厂",
        "Wu'an Jianshu Industry and Trade Co., Ltd. /武安市建树工贸有限公司",
        "Wu'an Jieshun Concentrator /武安市捷顺选厂",
        "Wu'an Kairun Mineral Processing Co., Ltd. /武安市凯润选矿有限公司",
        "Wu'an Lizhengwang Concentrator /武安市李正旺选矿厂",
        "Wu'an Litong Concentrator /武安市利通选矿厂",
        "Wu'an Lianshun Concentrator /武安市连顺选厂",
        "Wu'an Ruwang Concentrator /武安市如旺选矿厂",
        "Wu'an Shengfu Concentrator /武安市胜富选厂",
        "Wu'an Shenghua Concentrator /武安市盛华选矿厂",
        "Wu'an West Lake Xinhua Concentrator /武安市西湖新华选厂",
        "Wu'an Xitushan Xinyuan Concentrator /武安市西土山鑫源选厂",
        "Wu'an Dahezhuang Yuanxin Concentrator /武安市大贺庄源鑫选矿厂",
        "Wu'an Manfa Polymer Co., Ltd. /武安市满发聚有限公司",
        "Wu'an Yideshun Industry and Trade Co., Ltd. /武安市义得顺工贸有限公司",
        "Wu'an Gushan Xingsheng Concentrator /武安市固山兴盛选厂",
        "Wu'an Guolei Washing Co., Ltd./武安市国雷洗选有限公司",
        "Xiaowang Luchang Mineral Concentrator in Sizhuang Township, Wu'an City /武安市寺庄乡小汪禄昌选矿厂",
        "Wu'an Hongbao Washing Co., Ltd. /武安市鸿宝洗选有限公司",
        "Hebei Chenmei Industry and Trade Co., Ltd. /河北辰美工贸有限公司",
        "Wu'an Hongli Mineral Products Processing Factory /武安市宏利矿产品加工厂",
        "Wu'an Huadong Mineral Products Processing Factory /武安市华东矿产品加工厂",
        "Wu'an Jianshu Industry and Trade Co., Ltd. /武安市建树工贸有限公司",
        "Wu'an Jieshun Concentrator /武安市捷顺选厂",
        "Wu'an Kairun Mineral Processing Co., Ltd. /武安市凯润选矿有限公司",
        "Wu'an Lizhengwang Concentrator /武安市李正旺选矿厂",
        "Wu'an Litong Concentrator /武安市利通选矿厂",
        "Wu'an Lianshun Concentrator /武安市连顺选厂",
        "Wu'an Ruwang Concentrator /武安市如旺选矿厂",
        "Wu'an Shengfu Concentrator /武安市胜富选厂",
        "Wu'an Shenghua Concentrator /武安市盛华选矿厂",
    ],
    [
        "Wu'an Dongliang Stone Processing Factory /武安市东亮石料加工厂",
        "Wu'an Kanglei Building Materials Co., Ltd./武安市康磊建筑材料有限公司",
        "Wu'an Kong Xingshan Stone Processing Factory /武安市孔杏山石料加工厂",
        "Wu'an Leijin Stone Processing Factory /武安市磊金石料加工厂",
        "Limestone mine for construction in Baofeng, Wu'an /武安市宝峰建筑用石灰岩矿",
        "Wu'an Xicheng Stone Processing Factory /武安市喜成石料加工厂",
        "Wu'an Dayuan Building Materials Co., Ltd. /武安市大源建材有限公司",
        "Zhongxiang backfill processing plant /忠祥回填料加工厂",
        "Wu'an Xinshun Stone Processing Factory /武安市鑫顺石料加工厂",
        "Building of Wu'an Zhaocheng Trading Co., Ltd. /武安市兆诚贸易有限公司建筑 用石水尝旷",
        "Wu'an Suxin Quartz Stone Processing Factory /武安市苏鑫石英石加工厂",
        "Wu'an Dagang Industry and Trade Co., Ltd. /武安市大港工贸有限公司",
        "Wu'an Youhui Stone Processing Factory /武安市优辉石料加工厂",
        "Wu'an Xiangrong Stone Processing Factory /武安市祥荣石料加工厂",
        "Ruipeng Stone Processing Plant /瑞鹏石料加工厂",
        "Haisheng Stone Processing Factory /海盛石料加工厂",
        "Wu'an Huamian Stone Processing Factory /武安市华绵石料加工厂",
        "Zhenpeng Ore Processing Plant /振鹏矿石加工厂",
        "Wu'an Ruixin Stone Processing Factory /武安市瑞鑫石料加工厂",
        "Wu'an Shilei Stone Processing Factory /武安市石磊石子加工厂",
        "Wu'an Yimin Building Material Factory /武安市益民建材厂",
        "Wu'an Rongda Stone Processing Factory /武安市荣达石材加工厂",
        "Wu'an Baochuan Dolomite Factory /武安市宝川白云石厂",
        "Wu'an Laishun Stone Processing Factory /武安市来顺石料加工厂",
        "Wu'an City Wandering Suo Jinyugou Stone Factory /武安市徘徊锁金峪沟石料厂",
        "Wu'an Chenglou Building Materials Co., Ltd. /武安市诚樓建材有限公司",
        "Handan Zhulong New Building Materials Co., Ltd. /邯郸市筑龙新型建材有限公司",
        "Wu'an Pengli Stone Processing Co., Ltd. /武安市鹏励石料加工有限公司",
        "Wu'an Tiantai Building Materials Co., Ltd. /武安市天太建材有限公司",
        "Wu'an Veteran Stone Processing Factory /武安市老兵石子加工厂",
        "Wu'an Shuxing Stone Processing Factory /武安市淑兴石料加工厂",
        "Wu'an Hongfei Stone Processing Factory /武安市红飞石料加工厂",
        "Wu'an Huilin Stone Processing Factory /武安市会林石料加工厂",
        "Wu'an Leiqin Desulfurizer Co., Ltd. /武安市磊躱脱硫剂有限公司",
        "Wu'an Pengyang Stone Processing Factory /武安市鹏炀石料加工厂",
        "Stone processing plant of Wu'an Ruiteng Industry and Trade Co., Ltd. /武安市瑞腾工贸有限公司石子加工厂",
        "Hengguang Stone Processing Plant /恒光石料加工厂",
        "Hebei Suntech Building Materials Co., Ltd. /河北尚德建材有限公司",
        "Baisha Village Stone Factory, Shucun Town, Wu'an City /武安市淑村镇白沙村石料厂",
        "Wu'an Hengguang Stone Processing Factory /武安市恒光石料加工厂",
        "Wu'an Shunshun Stone Processing Factory /武安市顺顺石子加工厂",
        "Wanjie cement processing in Wu'an City /武安市万捷水泥加工",
        "Wu'an Yongcheng Stone Processing Factory /武安市永成石料加工厂",
        "Wu'an Ruiteng Industry and Trade Stone Factory /武安市锐腾工贸石料厂",
        "Wanjietong Stone Processing Plant in Maruasu City /丸安市万捷通石料加工厂",
        "Wu'an Shuntian Industry and Trade Co., Ltd. /武安市顺天工贸有限公司（石子）",
        "Wu'an Shihuanjin Stone Processing Factory /武安市石焕金石料加工厂",
        "Stone processing plant of Wu'an Kangfeng Economic and Trade Co., Ltd. /武安市康丰经贸有限公司石料加工厂",
        "Stone processing plant of Wu'an Huiteng Material Co., Ltd. /武安市慧腾物资有限公司石子加工厂",
        "Wu'an Anshun Building Materials Sales Co., Ltd. /武安市安顺建材销售有限公司",
        "Wu'an Gangqiang Stone Processing Factory /武安市钢强石料加工厂",
        "Wu'an Hengtong Stone Processing Factory /武安市恒通石料加工厂",
        "Wu'an Honglei Stone Processing Factory /武安市弘磊石料加工厂",
        "Wu'an Kuolei Stone Processing Factory /武安市阔磊石料加工厂",
        "Wu'an Mingzhi Building Refractory Material Factory /武安市明志建筑耐火材料厂",
        "Wu'an Chenli Stone Processing Factory /武安市辰利石料加工厂",
        "Wu'an Zhulong Economic and Trade Co., Ltd. /武安市铸隆经贸有限公司",
        "Wu'an Taijin Sand and Stone Sieving Factory /武安市泰金沙石分筛厂",
        "Wu'an Nanyang Yishan Calcium Industry Co., Ltd. /武安市南洋移山钙业有限公司（石子）",
        "Wu'an Langkuang Mineral Processing Plant /武安市琅矿石料加工厂",
        "Wu'an Hengsheng Stone Processing Factory /武安市恒升石料加工厂",
        "Wu'an Yidong Stone Processing Factory /武安市邑东石料加工厂",
    ],
    [
        "Wu'an Watson Industry and Trade Co., Ltd. /武安市沃森工贸有限公司",
        "Wu'an Jin'anling Industry and Trade Co., Ltd. /武安市金安岭工贸有限公司",
        "Wu'an Tiecheng Industry and Trade Co., Ltd. /武安市铁诚工贸有限公司",
        "Hebei Wantian New Mining Co., Ltd. /河北万天新矿业有限公司",
        "Wu'an Fangda Tuan Ball Factory /武安市方大团球厂",
        "Mineral processing of Yuanbaoshan Industrial Group, Wu'an City, Hebei Province /河北省武安市元宝山工业集团选矿",
    ],
    [
        "Wu'an Huian Industry and Trade Co., Ltd. / 武安市惠安工贸有限公司",
        "Wu'an Huaxu Fiber Technology Co., Ltd. / 武安市华旭纤维科技有限公司",
        "Wu'an Xianglu Trading Co., Ltd. / 武安市祥禄贸易有限公司",
        "Wu'an Jinyingshun Building Materials Co., Ltd. / 武安市金赢顺建材有限公司",
        "Wu'an Hengying Industry and Trade Co., Ltd. / 武安市恒盈工贸有限公司",
        "Wu'an Jinxuan Trading Co., Ltd. / 武安市金炫贸易有限公司",
    ],
    [
        "Jizhong Energy Handan Mining Group Julong Mining Co., Ltd. /冀中能源邯郸矿业集团聚隆矿业有限公司",
        "Jizhong Energy Fengfeng Group Co., Ltd. (Wannian Mine) /冀中能源峰峰集团有限公司（万年矿）",
        "Handan Guoerzhuang Mine of Jizhong Energy Co., Ltd. /冀中能源股份有限公司邯郸郭二庄矿",
        "Jizhong Energy Fengfeng Group Co., Ltd. /冀中能源峰峰集团有限公司大淑村矿",
        "Jizhong Energy Co., Ltd. /冀中能源股份有限公司邯郸云驾岭矿",
        "Wu'an Gensheng Coal Washing Co., Ltd. /武安市民生洗煤有限公司",
        "Wu'an Erfeng Industry and Trade Co., Ltd. /武安市尔丰工贸有限公司",
        "Wu'an Ruichuan Trading Co., Ltd. /武安市瑞川贸易有限公司",
        "Coal Washing Plant of Hebei Baichuan Industry and Trade Co., Ltd. /河北百川工贸有限公司洗煤厂",
        "Wu'an Deming Economic and Trade Co., Ltd. /武安市德铭经贸有限公司",
        "Wu'an Jingda Coal Washing Plant /武安市京达洗煤厂",
        "Handan Futian Washing Co., Ltd. /邯郸市富田洗选有限公司",
        "Wu'an Sanyou Economic and Trade Co., Ltd. /武安市三友经贸有限公司",
        "Wu'an Zhengsheng Coal Washing Plant /武安市正盛洗煤厂",
        "Wu'an Fuyitai Industry and Trade Co., Ltd. /武安市福益泰工贸有限责任公司",
        "Wu'an Liyang Coal Washing Co., Ltd. /武安市李杨煤炭洗选有限公司",
        "Fukang Coal Washing Plant, Cishan Juhuafu Village, Wu'an City /武安市磁山俱花富村富康洗煤厂",
        "Wu'an Baoping Coal Washing Co., Ltd. /武安市保平洗煤有限公司",
        "Wu'an Baoyu Industry and Trade Co., Ltd. /武安市宝煜工贸有限公司",
        "Wu'an Xinfa Coal Industry Co., Ltd. /武安市鑫发煤业有限公司",
        "Wu'an Wancheng Coal Washing Co., Ltd. /武安市万诚洗煤有限公司",
        "Wu'an Ruisen Industry and Trade Co., Ltd. /武安瑞森工贸有限公司",
        "Wu'an Nanxiang Industry and Trade Co., Ltd. /武安市南翔工贸有限公司",
        "Handan Shenglong Washing Co., Ltd. /邯郸市盛隆洗选有限责任公司",
        "Wu'an Sanming Coal Industry Co., Ltd. /武安市三明煤业有限公司",
        "Wu'an Yincheng Economic and Trade Co., Ltd. /武安市银成经贸有限公司",
        "Wu'an Purun Coal Washing Plant /武安市普润洗煤厂",
        "Wu'an Xingguang Materials Co., Ltd. /武安市兴广物资有限公司（武阳）",
        "Wu'an Nanyang Yishan Calcium Industry Co., Ltd. /武安市南洋移山钙业有限公司",
        "Wu'an Kaitai Materials Co., Ltd. /武安市开泰物资有限公司",
        "Wu'an Yuxingyuan Coal Washing Plant /武安市裕兴源洗煤厂",
        "Wu'an Juanyue Materials Co., Ltd. /武安市卷悦物资有限公司",
        "Wu'an Yongqing Coal Washing Plant /武安市永庆洗煤厂",
        "Wu'an Jinxinbao Materials Co., Ltd. /武安市金新宝物资有限公司",
        "Wu'an Dongshang Kuizeng Coal Washing Plant /武安市洞上奎增洗煤厂",
        "Wu'an Tongshengyuan Coal Washing Co., Ltd. /武安市同盛源洗煤有限公司",
        "Wu'an Guipeng Coal Washing Co., Ltd. /武安市贵鹏煤炭洗选有限公司",
        "Wu'an Qintai Trading Co., Ltd. /武安市秦泰贸易有限公司",
        "Wu'an Jintai Industry and Trade Co., Ltd. /武安市锦泰工贸有限公司",
        "Wu'an Changyun Materials Co., Ltd. /武安市长运物资有限贲任公司",
        "Wu'an Changwang Coal Washing Co., Ltd. /武安市昌旺洗煤有限公司",
        "Wu'an Tianer Industry and Trade Co., Ltd. /武安市天尔工贸有限公司",
        "Dai'an Xurui Coal Washing Plant /代安市旭锐洗煤厂",
        "Wu'an Lanxiang Coal Industry Co., Ltd /.武安市蓝翔煤业有限公司",
        "Wu'an Xiangsheng Materials Co., Ltd. /武安市祥胜物资有限公司",
        "Hebei Zhendong Coal Washing Co., Ltd. /河北振东煤炭洗选有限公司",
        "Wu'an Huidu Coal Industry Co., Ltd. /武安市惠都煤业有限公司",
        "Wu'an Jianhou Coal Washing Plant /武安市谗厚洗煤厂",
        "Wu'an Guantai Coal Washing Plant /武安市冠泰洗煤厂",
        "Wu'an Coal Preparation Plant /武安市选煤厂",
        "Wu'an Yinglin Industry and Trade Co., Ltd. /武安市英林工贸有限公司",
        "Wu'an Xinjuxiang Industry and Trade Co., Ltd. /武安市鑫聚祥工贸有限公司",
        "Wu'an Weisign Coal Washing Co., Ltd. /武安市伟签煤炭洗选有限公司",
        "Wu'an Jinyou Economic and Trade Co., Ltd. /武安市金友经贸有限公司",
        "Wu'an Shenxiang Economic and Trade Co., Ltd. /武安市神翔经贸有限公司",
        "Wu'an Yongjun Trading Co., Ltd. /武安市永军贸易有限公司",
        "Jizhong Energy Handan Mining Group Co., Ltd. /冀中能源邯郸矿业集团有限公司 康城煤矿洗煤厂",
        "Wu'an Dili Clean Coal Co., Ltd. /武安市地力洁净煤有限公司",
        "Hebei Huafeng Energy Technology Development Co., Ltd. /河北华丰能源科技发展 有限公司",
        "Wu'an Guangpu Coking Co., Ltd. /武安市广普焦化 有限公司",
        "Wu'an Baofeng Coal Coking Industry Co., Ltd. /武安市宝烽煤焦化工业 有限公司",
        "Xinxing Casting Pipe Co., Ltd. /新兴铸管股份有限公司",
        "Hebei Jinpeng Coal Chemical Industrial Co., Ltd. /河北金鹏煤化竖妒工业 有限公司",
        "Hebei Yuzhou Coal Chemical Industry Co., Ltd. /河北玉洲煤化工业股份 有限公司",
        "Hebei Tianyu Coal Chemical Power Co., Ltd. /河北天煜煤化电力 有限公司",
        "Wu'an Jinghui Qinggu Briquette Co., Ltd. /武安市晶辉清沽型煤有限公司",
        "Wu'an Bingcheng Clean Briquette Co., Ltd. /武安市炳诚洁净型煤有限公厂",
        "Wu'an Deming Trading Co., Ltd. /武安市徳铭贸易有限公司（型煤）",
        "Wu'an Canida Clean Briquette Co., Ltd. /武安市佳耐达洁净型煤有限公司",
        "Wu'an Qintai Trading Co., Ltd. /武安市秦泰贸易有限公司",
        "Wu'an Dili Clean Coal Co., Ltd. /武安市地力洁净煤有限公司",
        "Wu'an Xurui Coal Washing Plant-briquette /武安市旭锐洗煤厂-型煤",
        "Wu'an Minsheng Coal Washing Co., Ltd. /武安市民生洗煤有限公司-型煤",
        "Wu'an Jinzun Clean Briquette Co., Ltd. /武安市金樽洁净型煤有限公司",
        "Wu'an Aohang Clean Briquette Co., Ltd. /武安市澳航洁净型煤有限公司",
        "Wu'an Jiangmangqing Briquette Factory /武安市姜忙庆煤球厂",
        "Wu'an Guofeng Coal Ball Factory /武安市国丰煤球厂",
        "Wu'an Jijunming Briquette Factory /武安市籍俊明煤球厂",
        "Wu'an Yanzhen Briquette Factory /武安市严珍煤球厂",
        "Wu'an Baifunian Briquette Factory /武安市白付年煤球厂",
        "Wu'an Baizhanguo Coal Ball Factory /武安市白占国煤球厂",
        "Wu'an Limingchang Briquette Factory /武安市李明昌煤球厂",
        "Wu'an Mengjuan Coal Ball Factory /武安市孟娟煤球厂",
        "Wu'an Shiyongfu Briquette Factory /武安市史用復煤球厂",
        "Wu'an Xuepeng Briquette Factory /武安市学朋煤球厂",
        "Wu'an Guozengtian Coal Ball Factory /武安市郭增田煤球厂",
        "Wu'an Jiangguozheng Briquette Factory /武安市江国政煤球厂",
        "Wu'an Jumin Briquette Factory /武安市聚民煤球厂",
        "Wu'an Haiping Coal Ball Factory /武安市海平煤球厂",
        "Wu'an Wangqingjun Briquette Factory /武安市王庆军煤球厂",
        "Wu'an Fengshun Coal Ball Factory /武安市丰顺煤球厂",
        "Wu'an Wangxin Coal Ball Factory /武安市王鑫煤球厂",
        "Wu'an Yanzeng Coal Ball Factory /武安市彦增煤球厂",
        "Wu'an Tengwang Coal Ball Factory /武安市腾旺煤球厂",
        "Wu'an Xianchang Coal Ball Factory /武安市现昌煤球厂",
        "Wu'an Qingzeng Coal Ball Factory /武安市庆增煤球厂",
        "Wu'an Lvliu Environmental Protection Briquette Co., Ltd. /武安市绿柳环保型煤 有限公司",
        "Wu'an Taoyuan Briquette Factory /武安市桃园煤球厂",
        "Wu'an Changyu Industry and Trade Co., Ltd. /武安市畅宇工贸 有限公司",
        "Wu'an Guoyanxue Briquette Factory /武安市郭彦学煤球厂",
        "Wu'an Han Jianqiang Briquette Factory /武安市韩建强煤球厂",
        "Wu'an Xitushan Zhao Xianbin Coal Ball Factory /武安市西土山 赵现斌煤球厂",
        "Wu'an Caisen Economic and Trade Co., Ltd. /武安市财森经贸 有限责任公司",
    ],
];

export default data;
